import 'package:model_generator/model/model/enum_model.dart';
import 'package:model_generator/util/model_helper.dart';

class EnumModelWriter {
  final EnumModel jsonModel;

  const EnumModelWriter(this.jsonModel);

  String write() {
    final sb = StringBuffer()
      ..writeln(ModelHelper.autoGeneratedWarning)
      ..writeln()
      ..writeln("import 'package:json_annotation/json_annotation.dart';")
      ..writeln();

    final modelDescription = jsonModel.description?.trim();
    if (modelDescription != null && modelDescription.isNotEmpty) {
      sb.writeln("///$modelDescription");
    }

    sb.writeln('enum ${jsonModel.name} {');
    var first = true;
    jsonModel.fields?.forEach((key) {
      final jsonValue = key.value == null || key.value?.isEmpty == null
          ? key.serializedName
          : key.value;
      final description = key.description;

      if (first) {
        first = false;
      } else {
        sb.writeln(',');
      }
      if (description != null) {
        sb.writeln('  ///$description');
      }
      sb
        ..writeln("  @JsonValue('$jsonValue')")
        ..write("  ${key.name}('$jsonValue')");
    });
    if (jsonModel.fields?.isNotEmpty == true) {
      sb.writeln(';');
    }
    sb.writeln('');
    sb.writeln('  final String jsonValue;');
    sb.writeln('');
    sb.writeln('  const ${jsonModel.name}(this.jsonValue);');
    sb.writeln('}');

    if (jsonModel.generateMap) {
      sb
        ..writeln()
        ..writeln('const ${jsonModel.name}Mapping = {');

      jsonModel.fields?.forEach((key) {
        final jsonValue = key.value == null || key.value?.isEmpty == null
            ? key.serializedName
            : key.value;
        sb
          ..write('  ${jsonModel.name}.${key.name}: ')
          ..writeln('\'$jsonValue\',');
      });

      sb
        ..writeln('};')
        ..writeln()
        ..writeln('const reverse${jsonModel.name}Mapping = {');

      jsonModel.fields?.forEach((key) {
        final jsonValue = key.value == null || key.value?.isEmpty == null
            ? key.serializedName
            : key.value;
        sb
          ..write('  \'$jsonValue\': ')
          ..writeln('${jsonModel.name}.${key.name},');
      });

      sb.writeln('};');

      if (jsonModel.generateExtensions) {
        sb
          ..writeln()
          ..writeln(
              'extension ${jsonModel.name}Extension on ${jsonModel.name} {')
          ..writeln(
              '  String get stringValue => ${jsonModel.name}Mapping[this]!;')
          ..writeln('}')
          ..writeln()
          ..writeln('extension ${jsonModel.name}StringExtension on String {')
          ..writeln(
              '  ${jsonModel.name}? get as${jsonModel.name} => reverse${jsonModel.name}Mapping[this];')
          ..writeln('}');
      }
    }

    return sb.toString();
  }
}
