import 'dart:math';

import 'package:model_generator_example/model/book/book.dart';
import 'package:model_generator_example/model/book/book_category.dart';
import 'package:model_generator_example/model/user/person/gender.dart';
import 'package:model_generator_example/model/user/person/person.dart';

class BookUtil {
  static Book getBook() => Book(
        id: Random().nextInt(100000),
        name: getBookName(),
        author: getPerson(),
        publisher: maybeGet(getPerson),
        category: getCategory(),
        editors: getPersons(),
        translators: maybeGet(getPersons),
        isAvailable: Random().nextBool(),
        publishingDate: DateTime.now().subtract(Duration(days: Random().nextInt(1000))),
      );

  static T? maybeGet<T>(T Function() getter) {
    if (Random().nextBool()) {
      return getter();
    }
    return null;
  }

  static String getBookName() => bookNames[Random().nextInt(bookNames.length)];

  static Person getPerson() => Person(
        firstName: firstNames[Random().nextInt(firstNames.length)],
        lastName: '${firstNames[Random().nextInt(firstNames.length)]}sen',
        gender: Gender.values[Random().nextInt(Gender.values.length)],
      );

  static getCategory() => BookCategory.values[Random().nextInt(BookCategory.values.length)];

  static List<Person> getPersons() {
    final persons = <Person>[];
    for (var i = 0; i < Random().nextInt(5); i++) {
      persons.add(getPerson());
    }
    return persons;
  }

  static const List<String> bookNames = [
    'Hunting The Sun',
    'Death In My Wife',
    'Searching In The Night',
    'Leading The Slaves',
    'Question The Universe',
    'Death At The World',
    'Signs In The Jungle',
    'Sounds In The Shadows',
    'Avoiding My Husband',
    'Smiles In My Nightmares',
    'Losing The Champions',
    'Dead At Secrets',
    'Temptations In Myself',
    'Learning From The River',
    'Forsaken By The End',
    'Meeting In The Ashes',
    'Hunted By The Angels',
    'Hunted By The Fires',
    'Question My Destiny',
    'Symbols In The Country',
    'Forsaking The Shadows',
    'Arriving At My Friends',
    'Walking My School',
    'Life At A Storm',
    'Binding To The Demons',
    'Praised By The Moon',
    'Kicking The Elements',
    'Painting The Elements',
    'Cleaning Up The South',
    'Death To The Void',
  ];

  static List<String> firstNames = [
    'Liam',
    'Noah',
    'Oliver',
    'Elijah',
    'James',
    'William',
    'Benjamin',
    'Lucas',
    'Henry',
    'Theodore',
    'Jack',
    'Levi',
    'Alexander',
    'Jackson',
    'Mateo',
    'Daniel',
    'Michael',
    'Mason',
    'Sebastian',
    'Ethan',
    'Logan',
    'Owen',
    'Samuel',
    'Jacob',
    'Asher',
    'Aiden',
    'John',
    'Joseph',
    'Wyatt',
    'David',
    'Leo',
    'Luke',
    'Julian',
    'Hudson',
    'Grayson',
    'Matthew',
    'Ezra',
    'Gabriel',
    'Carter',
    'Isaac',
    'Jayden',
    'Luca',
    'Anthony',
    'Dylan',
    'Lincoln',
    'Thomas',
    'Maverick',
    'Elias',
    'Josiah',
    'Charles',
    'Caleb',
    'Christopher',
    'Ezekiel',
    'Miles',
    'Jaxon',
    'Isaiah',
    'Andrew',
    'Joshua',
    'Nathan',
    'Nolan',
    'Adrian',
    'Cameron',
    'Santiago',
    'Eli',
    'Aaron',
    'Ryan',
    'Angel',
    'Cooper',
    'Waylon',
    'Easton',
    'Kai',
    'Christian',
    'Landon',
    'Colton',
    'Roman',
    'Axel',
    'Brooks',
    'Jonathan',
    'Robert',
    'Jameson',
    'Ian',
    'Everett',
    'Greyson',
    'Wesley',
    'Jeremiah',
    'Hunter',
    'Leonardo',
    'Jordan',
    'Jose',
    'Bennett',
    'Silas',
    'Nicholas',
    'Parker',
    'Beau',
    'Weston',
    'Austin',
    'Connor',
    'Carson',
    'Dominic',
    'Xavier',
    'Jaxson',
    'Jace',
    'Emmett',
    'Adam',
    'Declan',
    'Rowan',
    'Micah',
    'Kayden',
    'Gael',
    'River',
    'Ryder',
    'Kingston',
    'Damian',
    'Sawyer',
    'Luka',
    'Evan',
    'Vincent',
    'Legend',
    'Myles',
    'Harrison',
    'August',
    'Bryson',
    'Amir',
    'Giovanni',
    'Chase',
    'Diego',
    'Milo',
    'Jasper',
    'Walker',
    'Jason',
    'Brayden',
    'Cole',
    'Nathaniel',
    'George',
    'Lorenzo',
    'Zion',
    'Luis',
    'Archer',
    'Enzo',
    'Jonah',
    'Thiago',
    'Theo',
    'Ayden',
    'Zachary',
    'Calvin',
    'Braxton',
    'Ashton',
    'Rhett',
    'Atlas',
    'Jude',
    'Bentley',
    'Carlos',
    'Ryker',
    'Adriel',
    'Arthur',
    'Ace',
    'Tyler',
    'Jayce',
    'Max',
    'Elliot',
    'Graham',
    'Kaiden',
    'Maxwell',
    'Juan',
    'Dean',
    'Matteo',
    'Malachi',
    'Ivan',
    'Elliott',
    'Jesus',
    'Emiliano',
    'Messiah',
    'Gavin',
    'Maddox',
    'Camden',
    'Hayden',
    'Leon',
    'Antonio',
    'Justin',
    'Tucker',
    'Brandon',
    'Kevin',
    'Judah',
    'Finn',
    'King',
    'Brody',
    'Xander',
    'Nicolas',
    'Charlie',
    'Arlo',
    'Emmanuel',
    'Barrett',
    'Felix',
    'Alex',
    'Miguel',
    'Abel',
    'Alan',
    'Beckett',
    'Amari',
    'Karter',
    'Timothy',
    'Abraham',
    'Jesse',
    'Zayden',
    'Blake',
    'Alejandro',
    'Dawson',
    'Tristan',
    'Victor',
    'Avery',
    'Joel',
    'Grant',
    'Eric',
    'Patrick',
    'Peter',
    'Richard',
    'Edward',
    'Andres',
    'Emilio',
    'Colt',
    'Knox',
    'Beckham',
    'Adonis',
    'Kyrie',
    'Matias',
    'Oscar',
    'Lukas',
    'Marcus',
    'Hayes',
    'Caden',
    'Remington',
    'Griffin',
    'Nash',
    'Israel',
    'Steven',
    'Holden',
    'Rafael',
    'Zane',
    'Jeremy',
    'Kash',
    'Preston',
    'Kyler',
    'Jax',
    'Jett',
    'Kaleb',
    'Riley',
    'Simon',
    'Phoenix',
    'Javier',
    'Bryce',
    'Louis',
    'Mark',
    'Cash',
    'Lennox',
    'Paxton',
    'Malakai',
    'Paul',
    'Kenneth',
    'Nico',
    'Kaden',
    'Lane',
    'Kairo',
    'Maximus',
    'Omar',
    'Finley',
    'Atticus',
    'Crew',
    'Brantley',
    'Colin',
    'Dallas',
    'Walter',
    'Brady',
    'Callum',
    'Ronan',
    'Hendrix',
    'Jorge',
    'Tobias',
    'Clayton',
    'Emerson',
    'Damien',
    'Zayn',
    'Malcolm',
    'Kayson',
    'Bodhi',
    'Bryan',
    'Aidan',
    'Cohen',
    'Brian',
    'Cayden',
    'Andre',
    'Niko',
    'Maximiliano',
    'Zander',
    'Khalil',
    'Rory',
    'Francisco',
    'Cruz',
    'Kobe',
    'Reid',
    'Daxton',
    'Derek',
    'Martin',
    'Jensen',
    'Karson',
    'Tate',
    'Muhammad',
    'Jaden',
    'Joaquin',
    'Josue',
    'Gideon',
    'Dante',
    'Cody',
    'Bradley',
    'Orion',
    'Spencer',
  ];
}
